name: Licensed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # prefer to use a full fetch for licensed workflows
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - uses: github/setup-licensed@v1
        with:
          version: '4.x'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/install-dependencies
      - run: licensed status
